# Generated by Django 5.0.7 on 2024-07-29 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_options_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Описание категории",
                null=True,
                verbose_name="Описание категории",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Название категории",
                max_length=50,
                verbose_name="Название категории",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Категория",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Products",
                to="catalog.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Дата создания",
                null=True,
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Описание продукта",
                null=True,
                verbose_name="Описание продукта",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Фото продукта",
                null=True,
                upload_to="product/photo/",
                verbose_name="Фото продукта",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                help_text="Название продукта",
                max_length=50,
                verbose_name="Название продукта",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.FloatField(
                blank=True, help_text="Цена", null=True, verbose_name="Цена"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Дата последнего изменения",
                null=True,
                verbose_name="Дата последнего изменения",
            ),
        ),
    ]
