# Generated by Django 5.0.7 on 2024-08-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_contacts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogrecord",
            name="is_published",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Опубликовано"
            ),
        ),
    ]
