# Generated by Django 5.0.7 on 2024-08-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_blogrecord_is_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contacts",
            options={"verbose_name": "Обращение", "verbose_name_plural": "Обращения"},
        ),
        migrations.AlterField(
            model_name="blogrecord",
            name="count",
            field=models.IntegerField(default=0, verbose_name="Количество просмотров"),
        ),
    ]
