# Generated by Django 5.0.7 on 2024-08-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_contacts_options_alter_blogrecord_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogrecord",
            name="slug",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="slug"
            ),
        ),
    ]
