# Generated by Django 5.0.7 on 2024-09-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_alter_version_num_vers_alter_version_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="num_vers",
            field=models.PositiveIntegerField(
                blank=True, null=True, unique=True, verbose_name="Номер версии"
            ),
        ),
    ]
