# Generated by Django 5.0.7 on 2024-09-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_alter_version_num_vers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="num_vers",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Номер версии"
            ),
        ),
    ]
