# Generated by Django 5.0.7 on 2024-09-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_alter_version_num_vers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="is_current_vers",
            field=models.BooleanField(default=False, verbose_name="Текущая версия"),
        ),
    ]
