# Generated by Django 5.0.7 on 2024-09-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_alter_version_is_current_vers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="num_vers",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Номер версии"
            ),
        ),
    ]
