# Generated by Django 4.2 on 2024-12-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0017_blogrecord_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("name", "category", "price"),
                "permissions": [("can_unpublish_product", "can unpublish product")],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Опубликовано"
            ),
        ),
    ]
